[package]
name = "validate_soduku_with_size_nxn"
version = "0.1.0"
authors = ["Seth <swidoff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
